FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/core ./src/core
COPY src/parsing ./src/parsing

CMD ["python", "-m", "src.parsing.main"]
