services:
  # --- Telegram-бот ---
  bot:
    build:
      context: .
      dockerfile: src/bot/Dockerfile-bot   # путь к Dockerfile
    container_name: vkr_bot
    env_file:
      - .env
    volumes:
      - ./src/bot:/app/src/bot
      - ./src/core:/app/src/core
    command: ["python", "-m", "src.bot.main"]
    restart: unless-stopped

  # --- Парсер мероприятий ---
  parser:
    build:
      context: .
      dockerfile: src/parsing/Dockerfile-parser
    container_name: vkr_parser
    env_file:
      - .env
    volumes:
      - ./src/parsing:/app/src/parsing
      - ./src/core:/app/src/core
    command: ["python", "-m", "src.parsing.main"]
    restart: unless-stopped
