

services:
  # --- Telegram-бот ---
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
    container_name: vkr_bot
    env_file:
      - .env
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - TZ=Europe/Moscow
    volumes:
      - ./src:/app/src
    command: ["python", "-m", "src.bot.main"]
    restart: unless-stopped

  # --- Парсер мероприятий ---
  parser:
    build:
      context: .
      dockerfile: docker/Dockerfile.parser
    container_name: vkr_parser
    env_file:
      - .env
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - TZ=Europe/Moscow
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER=/usr/bin/chromedriver
    shm_size: "1gb"
    volumes:
      - ./src:/app/src
    command: ["python", "-m", "src.parsing.main"]
    restart: unless-stopped
